apiVersion: apps/v1
kind: Deployment
metadata:
  name: oomkill-deploy-demo
  namespace: k8swhisperer-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oomkill-demo
  template:
    metadata:
      labels:
        app: oomkill-demo
    spec:
      containers:
      - name: memory-hog
        image: polinux/stress
        command: ["stress"]
        args: ["--vm", "1", "--vm-bytes", "200M", "--vm-hang", "1"]
        resources:
          limits:
            memory: "50Mi"
          requests:
            memory: "50Mi"
