"""Auto-generate GitHub PRs for permanent config fixes."""

import logging
import subprocess
import json
import os
from pathlib import Path
from datetime import datetime, timezone

logger = logging.getLogger(__name__)

def create_config_fix_pr(
    incident_id: str,
    deployment_name: str,
    namespace: str,
    action: str,
    params: dict,
    diagnosis: str,
) -> dict:
    """Create a GitHub PR with the permanent config fix.

    Returns {"status": "success/error", "pr_url": "...", ...}
    """
    try:
        # Check if we're in a git repo and gh is available
        result = subprocess.run(["gh", "auth", "status"], capture_output=True, text=True, timeout=10)
        if result.returncode != 0:
            logger.warning("gh CLI not authenticated, skipping PR creation")
            return {"status": "skipped", "reason": "gh CLI not authenticated"}

        # Get the repo root
        repo_root = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True, text=True, timeout=5, cwd=os.getcwd()
        ).stdout.strip()

        if not repo_root:
            return {"status": "skipped", "reason": "not in a git repository"}

        # Strip kind prefix (e.g. "deployment/name" -> "name")
        if "/" in deployment_name:
            deployment_name = deployment_name.split("/", 1)[-1]

        # Create a branch name
        branch_name = f"k8swhisperer/fix-{incident_id[:8]}-{deployment_name}"
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")

        # Generate the fix content based on action type
        fix_content = _generate_fix_yaml(deployment_name, namespace, action, params)
        if not fix_content:
            return {"status": "skipped", "reason": f"no config fix needed for action: {action}"}

        # Write the fix to a file
        fix_dir = Path(repo_root) / "k8s" / "fixes"
        fix_dir.mkdir(parents=True, exist_ok=True)
        fix_file = fix_dir / f"fix-{incident_id[:8]}-{deployment_name}.yaml"
        fix_file.write_text(fix_content)

        # Create branch, commit, push, and create PR
        cmds = [
            ["git", "checkout", "-b", branch_name],
            ["git", "add", str(fix_file)],
            ["git", "commit", "-m", f"fix({deployment_name}): {action} - auto-generated by K8sWhisperer\n\nIncident: {incident_id}\nDiagnosis: {diagnosis[:200]}"],
            ["git", "push", "-u", "origin", branch_name],
        ]

        for cmd in cmds:
            r = subprocess.run(cmd, capture_output=True, text=True, timeout=30, cwd=repo_root)
            if r.returncode != 0:
                logger.warning("Git command failed: %s -> %s", cmd, r.stderr)
                # Try to cleanup
                subprocess.run(["git", "checkout", "-"], capture_output=True, cwd=repo_root)
                return {"status": "error", "reason": f"git command failed: {r.stderr[:200]}"}

        # Create PR
        pr_body = f"""## Auto-Generated Config Fix by K8sWhisperer

**Incident:** `{incident_id}`
**Deployment:** `{deployment_name}` in namespace `{namespace}`
**Action:** `{action}`

### Diagnosis
{diagnosis[:500]}

### What Changed
This PR applies the permanent version of the runtime fix that K8sWhisperer applied to resolve the incident.

### Parameters
```json
{json.dumps(params, indent=2)}
```

---
*This PR was auto-generated by K8sWhisperer's incident response pipeline.*
"""

        pr_result = subprocess.run(
            ["gh", "pr", "create", "--title", f"fix({deployment_name}): {action}", "--body", pr_body],
            capture_output=True, text=True, timeout=30, cwd=repo_root
        )

        # Switch back to the original branch
        subprocess.run(["git", "checkout", "-"], capture_output=True, cwd=repo_root)

        if pr_result.returncode == 0:
            pr_url = pr_result.stdout.strip()
            logger.info("Created PR: %s", pr_url)
            return {"status": "success", "pr_url": pr_url, "branch": branch_name}
        else:
            logger.warning("PR creation failed: %s", pr_result.stderr)
            return {"status": "error", "reason": pr_result.stderr[:200]}

    except Exception as e:
        logger.exception("Failed to create config fix PR")
        return {"status": "error", "reason": str(e)}


def _generate_fix_yaml(deployment_name: str, namespace: str, action: str, params: dict) -> str | None:
    """Generate a Kubernetes YAML patch for the config fix."""
    if action == "patch_deployment_resources":
        memory = params.get("memory_limit", "256Mi")
        cpu = params.get("cpu_limit", "")

        resources = {"limits": {}}
        if memory:
            resources["limits"]["memory"] = memory
        if cpu:
            resources["limits"]["cpu"] = cpu

        return f"""# Auto-generated by K8sWhisperer
# Apply with: kubectl apply -f <this-file>
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {deployment_name}
  namespace: {namespace}
spec:
  template:
    spec:
      containers:
      - name: {deployment_name}
        resources:
          limits:
            memory: "{memory}"
{f'            cpu: "{cpu}"' if cpu else ''}
"""

    if action == "rollback_deployment":
        return f"""# Auto-generated by K8sWhisperer
# This deployment was rolled back at runtime.
# Review and update the deployment spec to prevent recurrence.
# kubectl rollout undo deployment/{deployment_name} -n {namespace}
"""

    return None
